//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisServices2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VertexFactorsDb
    {
        public long vertex_id { get; set; }
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public double betweenness_centrality { get; set; }
        public double closeness_centrality { get; set; }
        public double indegree_centrality { get; set; }
        public double influence_range { get; set; }
        public double outdegree_centrality { get; set; }
        public bool up_to_date { get; set; }
        public long network_id { get; set; }
    
        public virtual VertexDb VertexDb { get; set; }
    }
}
