//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkFactorsDb
    {
        public long id { get; set; }
        public long network_id { get; set; }
        public System.DateTime date { get; set; }
        public double density { get; set; }
        public bool up_to_date { get; set; }
        public double avg_betweenness_centrality { get; set; }
        public double avg_closeness_centrality { get; set; }
        public double avg_indegree_centrality { get; set; }
        public double avg_influence_range { get; set; }
        public double avg_outdegree_centrality { get; set; }
    
        public virtual NetworkDb NetworkDb { get; set; }
    }
}
